name: Run tests

defaults:
  run:
    shell: zsh -e {0}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Run linter for pyspec
        run: |
          make lint
          git diff --exit-code

  whitespace:
    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Check for trailing whitespace
        run: |
          if git grep -n '[[:blank:]]$'; then
            echo "Trailing whitespace found. Please fix it."
            exit 1
          fi

  comments:
    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Check fork comments
        run: python3 scripts/check_fork_comments.py

  tests:
    needs: [lint, whitespace, comments]
    runs-on: [self-hosted-ghr-custom, size-xl-x64, profile-consensusSpecs]
    strategy:
      matrix:
        fork:
          - phase0
          - altair
          - bellatrix
          - capella
          - deneb
          - electra
          - fulu
          - eip7732
          - eip7805
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Run pyspec tests for ${{ matrix.fork }}
        run: make test preset=minimal fork=${{ matrix.fork }}
